#!/bin/bash

case "$1" in
  start)
    start-stop-daemon --start --name aesdsocket --startas /usr/bin/aesdsocket -- -d
    ;;
  stop)
    start-stop-daemon --stop --name aesdsocket
    ;;
  *)
    echo "Usage: $0 {start|stop}" >&2
  exit 1
esac
